language: clojure
script:
- lein build
jdk:
- oraclejdk8
notifications:
  slack:
    secure: CZ0kK7RXhXPGsKtH2LDNXBXNlB3BCyrXwAaNkE2H7cY5oJb/3L4aY6dRVEY+5R2DvBeuH8rsCCANJs/lv3FT0u+vUAsHH/1cAd5fCes/VisrZYdDhw36HDIt1fw5Q7FNczniTBEQUfIXI0GFYkl3VDOSfJrRyF+2Fiho9d9qGzbsUzG+tsv8ydtp3VFi/+PnAvQIpMZTBOf/hibEX8/WUamDqeQg4sy9pVxPvSWygeztNF+5VVn1ELhPyeARKoHbS7j7BTOsaPi0Tg9ag8FxfHTzU4QpqvA7mZWDMnN7W/c6cp6uzV5db2z+85o7ua747kTpFtk/gTE+0ceFhLyP9r+SYwC7rbrEIFaKdlgsgYuVvXLfOPm6/HUj3pP15rW2SF52zjaULUC3tIDnNNgOu1HAdNTR/ChY7iktPOROz1WRZcle3P6JVByS6jKONz0p/BIzKbM1TCLtPDjO0qcWDVXvLylRFmOd52L4LOpkpe+4wRxWCFWM5meXTM5Jrmv/eLbYLencn2SAotUejfra4RkSY8suFjeaDnjhd0MaISjjwW1S8PtbL2rVX9CrogWPwFtOpN3XuC6e5bnwLeRqbcohu43YVWsuIXLTkw9XgoDKoR0FixksLkz7y9cl4w9tl2HYswZubL1Mxj1V0osIqEa64JmddA/eXBD1b+5pQPA=
